# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(500, 500)
        self.background = QtWidgets.QLabel(Form)
        self.background.setGeometry(QtCore.QRect(-20, -40, 1621, 1081))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("../../../../../usr/share/applications/background.jpg"))
        self.background.setObjectName("background")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 125, 100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../usr/share/applications/icon.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(130, 260, 240, 15))
        self.label_2.setStyleSheet("color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 300, 240, 31))
        self.plainTextEdit.setStyleSheet("color:white;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(135, 360, 230, 50))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setAccessibleName("")
        self.pushButton_2.setStyleSheet("color: black;\n"
"background-color: rgb(255, 53, 56);\n"
"border-color: rgb(93, 0, 1);\n"
"border-radius: 25px 25px;\n"
"hover {\n"
"    background-color: #4CAF50; /* Green */\n"
"    color: white;}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Пароль"))
        self.label_2.setText(_translate("Form", "Введите пароль администратора"))
        self.pushButton_2.setText(_translate("Form", "Далее"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
